import React from 'react';
import { Container, Row, Col } from 'react-bootstrap';
import LandingNavbar from '../navbar/LandingNavbar';
import GlobalFooter from '../footer/GlobalFooter';
import '../css/PrivacyPage.css'; // Ensure you have this CSS file or use an existing one

function PrivacyPolicyPage() {
  return (
    <div className="privacy-policy-page" mb-5>
      <LandingNavbar />
      <Container className="privacy-policy-page">
        <Row>
          <Col lg={12}>
            <h2 className='privacy-affiliation'>My ClickUp Portal operates independently and is not affiliated with, endorsed, or sponsored by ClickUp or any of its subsidiaries.</h2>
            <h2 className='privacy-h2'>Privacy Policy</h2>
            <p className='privacy-p'>Effective date: 05/02/24</p>
            <p className='privacy-p'>Welcome to ClickUP Portal ("we", "us", or "our"). Our Privacy Policy explains how we collect, use, and protect information in relation to our mobile app and website (collectively, the "Service"), currently in development.</p>
            <h3 className='privacy-h3'>Information Collection and Use</h3>
            <p className='privacy-p'>For the purpose of running and improving the Service during its development stage, we do not collect any personal information from users. Any data generated or used by the app is solely for operational functionality and is not shared, sold, or distributed to any third parties.</p>
            <h3 className='privacy-h3'>Data Security</h3>
            <p className='privacy-p'>We strive to implement reasonable security measures to protect any data that may be generated by the Service. However, due to the inherent nature of the internet and electronic communications, we cannot guarantee absolute security of any information.</p>
            <h3 className='privacy-h3'>Children's Privacy</h3>
            <p className='privacy-p'>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from children under 13.</p>
            <h3 className='privacy-h3'>Limitation of Liability</h3>
            <p className='privacy-p'>ClickUP Portal is not responsible for any losses, damages, claims, or issues arising from the use of our Service. The Service is provided on an "as is" and "as available" basis, and your use of it is at your sole risk.</p>
            <h3 className='privacy-h3'>Changes to This Privacy Policy</h3>
            <p className='privacy-p'>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>
            <h3 className='privacy-h3'>Contact Us</h3>
            <p className='privacy-p'>If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact us at info@gurver.org.</p>
          </Col>
        </Row>
      </Container>
      <GlobalFooter />
    </div>
  );
}

export default PrivacyPolicyPage;
