name: Deploy Express App

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd my-customer-app &&
            git pull &&
            PROXY="${{ secrets.PROXY }}" &&
            if [ -x "$(command -v jq)" ]; then
              jq '.proxy = env.PROXY' package.json > package.json.tmp && mv package.json.tmp package.json
            else
              echo "jq is not installed. Cannot update proxy."
              exit 1
            fi &&
            npm install &&
            pm2 reload my-customer-app || pm2 start npm -- start --name my-customer-app --watch
